---
# Dependabot is a service that automates dependency updates for GitHub projects.

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    # Ignore patch versions of dependencies
    dependency-name: "*"
    update-types: ["version-update:semver-patch"]
