[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.py_cache
  | \.venv
)/
'''

[tool.isort]
profile = "black"
use_parentheses = true
line_length = 120
combine_as_imports = true
from_first = true # put the 'from' imports first
